version: "3.9"

services:
  postgres:
    restart: unless-stopped
    image: postgres:15.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_DB: 'nostter'
      POSTGRES_USER: 'nostter'
      POSTGRES_PASSWORD: 'nostter'

  nostter-backend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.nostter-backend
    ports:
      - '3003:3003'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://nostter:nostter@postgres:5432/nostter?schema=public'

volumes:
  postgres:
