name: E2E Tests

on:
  deployment_status: {}
  workflow_dispatch: {}

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn --immutable
    - run: yarn ava
      working-directory: packages/nostter-e2e-tests
